// Terraform HCL Infrastructure Exporter (Phase 11B)

export interface TerraformModuleBundle {
  mainTf: string;
  variablesTf: string;
  outputsTf: string;
}

/**
 * Generates production-ready Terraform HCL infrastructure modules for client cross-account IAM monitoring role setup.
 */
export function generateTerraformModule(
  accountNumber: string = "123456789012",
  externalId: string = "sentinel-ext-vault-key-99"
): TerraformModuleBundle {
  const mainTf = `# RDS Sentinel Cross-Account IAM Monitoring Role Module
# Automatically generated by AWS RDS Sentinel Console

terraform {
  required_version = ">= 1.0.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

resource "aws_iam_role" "rds_sentinel_monitoring_role" {
  name        = var.monitoring_role_name
  description = "Cross-account read-only telemetry monitoring role for AWS RDS Sentinel SaaS"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Principal = {
          AWS = "arn:aws:iam::\${var.sentinel_saas_account_id}:root"
        }
        Condition = {
          StringEquals = {
            "sts:ExternalId" = var.external_id
          }
        }
      }
    ]
  })

  tags = {
    Environment = "Production"
    ManagedBy   = "Terraform"
    Application = "RDS-Sentinel"
  }
}

resource "aws_iam_role_policy_attachment" "rds_read_only" {
  role       = aws_iam_role.rds_sentinel_monitoring_role.name
  policy_arn = "arn:aws:iam::aws:policy/AmazonRDSReadOnlyAccess"
}

resource "aws_iam_role_policy_attachment" "cloudwatch_read_only" {
  role       = aws_iam_role.rds_sentinel_monitoring_role.name
  policy_arn = "arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess"
}
`;

  const variablesTf = `# Terraform Input Variables for RDS Sentinel Setup

variable "sentinel_saas_account_id" {
  type        = string
  description = "AWS Account ID of the RDS Sentinel SaaS Ingestion System"
  default     = "${accountNumber}"
}

variable "external_id" {
  type        = string
  description = "Cryptographic External ID required for STS AssumeRole authorization"
  default     = "${externalId}"
}

variable "monitoring_role_name" {
  type        = string
  description = "Name of the cross-account IAM role to synthesize"
  default     = "RDSSentinelMonitoringRole"
}
`;

  const outputsTf = `# Terraform Outputs for RDS Sentinel Monitoring Stack

output "monitoring_role_arn" {
  value       = aws_iam_role.rds_sentinel_monitoring_role.arn
  description = "ARN of the created RDS Sentinel Cross-Account IAM Monitoring Role"
}

output "external_id_verified" {
  value       = var.external_id
  sensitive   = true
  description = "Validated External ID used for role trust policy"
}
`;

  return {
    mainTf,
    variablesTf,
    outputsTf,
  };
}

/**
 * Trigger browser file download of Terraform HCL main.tf
 */
export function downloadTerraformFile(
  content: string,
  filename: string = "main.tf"
): void {
  if (typeof window === "undefined") return;
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
